receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

processors:
  resource:
    attributes:
      - key: service.name
        value: OTLP Exporter
        action: insert
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [resource, batch]
